# Generated by Django 6.0 on 2026-03-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentcompany',
            name='account_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='parentcompany',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='parentcompany',
            name='gst_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='parentcompany',
            name='pan_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='parentcompany',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='parentcompany',
            name='tan_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
