# Generated by Django 6.0 on 2026-03-12 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esn', models.CharField(max_length=50, unique=True)),
                ('imei', models.CharField(max_length=50, unique=True)),
                ('iccid', models.CharField(max_length=50)),
                ('telecom_provider_1', models.CharField(blank=True, max_length=100)),
                ('telecom_provider_2', models.CharField(blank=True, max_length=100)),
                ('msisdn_1', models.CharField(blank=True, max_length=20)),
                ('msisdn_2', models.CharField(blank=True, max_length=20)),
                ('esim_status', models.CharField(blank=True, max_length=20)),
                ('esim_validity', models.DateField(blank=True, null=True)),
                ('stock_status', models.CharField(default='in_stock', max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('assigned_to', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='mapwala_mis.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
