# Generated by Django 6.0 on 2026-01-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0002_quotation_quotationitem_quotationsequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinformation',
            name='state_of_supply',
            field=models.CharField(choices=[('RAW', 'Raw Material'), ('WIP', 'Work in Progress'), ('FG', 'Finished Goods'), ('SFG', 'Semi-Finished'), ('CON', 'Consumable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='deviceinformation',
            name='unit_of_measure',
            field=models.CharField(choices=[('PCS', 'Pieces (PCS)'), ('KG', 'Kilograms (KG)'), ('G', 'Grams (G)'), ('M', 'Meters (M)'), ('CM', 'Centimeters (CM)'), ('L', 'Liters (L)'), ('ML', 'Milliliters (ML)')], max_length=20),
        ),
    ]
