# Generated by Django 6.0 on 2026-03-16 05:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0002_deviceinventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Rate (₹)')),
                ('gst_rate', models.DecimalField(choices=[(Decimal('0.00'), '0%'), (Decimal('5.00'), '5%'), (Decimal('12.00'), '12%'), (Decimal('18.00'), '18%'), (Decimal('28.00'), '28%')], decimal_places=2, max_digits=5, verbose_name='GST Rate')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Gross Amount (₹)')),
                ('delivery_date', models.DateField(verbose_name='Delivery Date')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='b2b_orders', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='b2b_orders', to='mapwala_mis.purchaseorder', verbose_name='Purchase Order')),
                ('supply_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='b2b_orders', to='mapwala_mis.state', verbose_name='Supply State')),
            ],
            options={
                'verbose_name': 'B2B Order',
                'verbose_name_plural': 'B2B Orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['purchase_order'], name='mapwala_mis_purchas_3661c1_idx'), models.Index(fields=['supply_state'], name='mapwala_mis_supply__a42c17_idx'), models.Index(fields=['-created_at'], name='mapwala_mis_created_875107_idx')],
            },
        ),
    ]
