# Generated by Django 6.0 on 2026-03-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0002_alter_parentcompany_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestforquote',
            name='additional_requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
