# Generated by Django 6.0 on 2026-01-06 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0003_parentcompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('bank_name', models.CharField(max_length=255)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('gst_number', models.CharField(max_length=20)),
                ('gst_document', models.FileField(upload_to='documents/vendor/gst/')),
                ('tan_number', models.CharField(max_length=20)),
                ('tan_document', models.FileField(upload_to='documents/vendor/tan/')),
                ('pan_number', models.CharField(max_length=20)),
                ('pan_document', models.FileField(upload_to='documents/vendor/pan/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapwala_mis.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapwala_mis.state')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
