# Generated by Django 6.0 on 2026-03-16 05:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0004_alter_b2border_gst_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2border',
            name='gst_rate',
            field=models.DecimalField(choices=[(Decimal('0.00'), '0%'), (Decimal('5.00'), '5%'), (Decimal('12.00'), '12%'), (Decimal('18.00'), '18%'), (Decimal('28.00'), '28%')], decimal_places=2, max_digits=5, verbose_name='GST Rate'),
        ),
    ]
