# Generated by Django 6.0 on 2026-01-07 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0004_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2CCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('bank_name', models.CharField(max_length=255)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('gst_number', models.CharField(max_length=20)),
                ('gst_document', models.FileField(upload_to='documents/b2c/gst/')),
                ('tan_number', models.CharField(max_length=20)),
                ('tan_document', models.FileField(upload_to='documents/b2c/tan/')),
                ('pan_number', models.CharField(max_length=20)),
                ('pan_document', models.FileField(upload_to='documents/b2c/pan/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='parentcompany',
            index=models.Index(fields=['gst_number'], name='mapwala_mis_gst_num_75b0e5_idx'),
        ),
        migrations.AddIndex(
            model_name='parentcompany',
            index=models.Index(fields=['pan_number'], name='mapwala_mis_pan_num_c5f5c0_idx'),
        ),
        migrations.AddField(
            model_name='b2ccustomer',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapwala_mis.district'),
        ),
        migrations.AddField(
            model_name='b2ccustomer',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapwala_mis.state'),
        ),
        migrations.AddIndex(
            model_name='b2ccustomer',
            index=models.Index(fields=['gst_number'], name='mapwala_mis_gst_num_a22a94_idx'),
        ),
        migrations.AddIndex(
            model_name='b2ccustomer',
            index=models.Index(fields=['pan_number'], name='mapwala_mis_pan_num_2c23fe_idx'),
        ),
        migrations.AddIndex(
            model_name='b2ccustomer',
            index=models.Index(fields=['phone_number'], name='mapwala_mis_phone_n_5efbe2_idx'),
        ),
    ]
