# Generated by Django 6.0 on 2026-01-07 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0005_b2ccustomer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('bank_name', models.CharField(max_length=255)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('gst_number', models.CharField(max_length=20)),
                ('gst_document', models.FileField(upload_to='documents/b2b/gst/')),
                ('tan_number', models.CharField(max_length=20)),
                ('tan_document', models.FileField(upload_to='documents/b2b/tan/')),
                ('pan_number', models.CharField(max_length=20)),
                ('pan_document', models.FileField(upload_to='documents/b2b/pan/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapwala_mis.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapwala_mis.state')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['gst_number'], name='mapwala_mis_gst_num_59c45a_idx'), models.Index(fields=['pan_number'], name='mapwala_mis_pan_num_e32ff9_idx'), models.Index(fields=['phone_number'], name='mapwala_mis_phone_n_6d7e7d_idx')],
            },
        ),
    ]
