# Generated by Django 6.0 on 2026-01-08 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0006_b2bpartner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('bank_name', models.CharField(max_length=255)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('gst_number', models.CharField(max_length=20)),
                ('gst_document', models.FileField(upload_to='documents/distributor/gst/')),
                ('tan_number', models.CharField(max_length=20)),
                ('tan_document', models.FileField(upload_to='documents/distributor/tan/')),
                ('pan_number', models.CharField(max_length=20)),
                ('pan_document', models.FileField(upload_to='documents/distributor/pan/')),
                ('linked_to', models.CharField(choices=[('manufacturer', 'Manufacturer')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorised_district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorised_distributors', to='mapwala_mis.district')),
                ('authorised_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorised_distributors', to='mapwala_mis.state')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributors', to='mapwala_mis.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributors', to='mapwala_mis.state')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distributors', to='mapwala_mis.manufacturer')),
            ],
        ),
    ]
