# Generated by Django 6.0 on 2026-01-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0007_manufacturer_distributor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor',
            name='authorised_district',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='authorised_state',
        ),
        migrations.AddField(
            model_name='distributor',
            name='authorised_districts',
            field=models.ManyToManyField(blank=True, related_name='authorised_distributors', to='mapwala_mis.district'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='authorised_states',
            field=models.ManyToManyField(blank=True, related_name='authorised_distributors', to='mapwala_mis.state'),
        ),
    ]
