# Generated by Django 6.0 on 2026-01-08 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0008_remove_distributor_authorised_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('bank_name', models.CharField(max_length=255)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('gst_number', models.CharField(max_length=20)),
                ('gst_document', models.FileField(upload_to='documents/dealer/gst/')),
                ('tan_number', models.CharField(max_length=20)),
                ('tan_document', models.FileField(upload_to='documents/dealer/tan/')),
                ('pan_number', models.CharField(max_length=20)),
                ('pan_document', models.FileField(upload_to='documents/dealer/pan/')),
                ('linked_to', models.CharField(choices=[('manufacturer', 'Manufacturer'), ('distributor', 'Distributor')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorised_districts', models.ManyToManyField(blank=True, related_name='authorised_dealers', to='mapwala_mis.district')),
                ('authorised_states', models.ManyToManyField(blank=True, related_name='authorised_dealers', to='mapwala_mis.state')),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dealers', to='mapwala_mis.distributor')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dealers', to='mapwala_mis.district')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dealers', to='mapwala_mis.manufacturer')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dealers', to='mapwala_mis.state')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
