# Generated by Django 6.0 on 2026-01-08 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0009_dealer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealer',
            options={'ordering': ['-id'], 'verbose_name': 'Dealer', 'verbose_name_plural': 'Dealers'},
        ),
        migrations.AlterField(
            model_name='dealer',
            name='account_holder_name',
            field=models.CharField(max_length=255, verbose_name='Account Holder Name'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='account_number',
            field=models.CharField(max_length=50, verbose_name='Bank Account Number'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='authorised_districts',
            field=models.ManyToManyField(blank=True, help_text='Districts where this dealer is allowed to operate. Each district must belong to one of the selected authorised states.', related_name='authorised_dealers', to='mapwala_mis.district', verbose_name='Authorised Operating Districts'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='authorised_states',
            field=models.ManyToManyField(blank=True, help_text='States where this dealer is allowed to operate.', related_name='authorised_dealers', to='mapwala_mis.state', verbose_name='Authorised Operating States'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='bank_name',
            field=models.CharField(max_length=255, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='distributor',
            field=models.ForeignKey(blank=True, help_text='Required when Linked To is Distributor.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dealers', to='mapwala_mis.distributor', verbose_name='Linked Distributor'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='district',
            field=models.ForeignKey(help_text='District where the dealer is officially registered.', on_delete=django.db.models.deletion.PROTECT, related_name='dealers', to='mapwala_mis.district', verbose_name='Registered District'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='gst_document',
            field=models.FileField(upload_to='documents/dealer/gst/', verbose_name='GST Document'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='gst_number',
            field=models.CharField(max_length=20, verbose_name='GST Number'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='ifsc_code',
            field=models.CharField(max_length=20, verbose_name='IFSC Code'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='linked_to',
            field=models.CharField(choices=[('manufacturer', 'Manufacturer'), ('distributor', 'Distributor')], help_text='Choose whether this dealer is linked to a Manufacturer or Distributor.', max_length=20, verbose_name='Linked To'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Required when Linked To is Manufacturer.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dealers', to='mapwala_mis.manufacturer', verbose_name='Linked Manufacturer'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Dealer Name'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='pan_document',
            field=models.FileField(upload_to='documents/dealer/pan/', verbose_name='PAN Document'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='pan_number',
            field=models.CharField(max_length=20, verbose_name='PAN Number'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='state',
            field=models.ForeignKey(help_text='State where the dealer is officially registered.', on_delete=django.db.models.deletion.PROTECT, related_name='dealers', to='mapwala_mis.state', verbose_name='Registered State'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='tan_document',
            field=models.FileField(upload_to='documents/dealer/tan/', verbose_name='TAN Document'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='tan_number',
            field=models.CharField(max_length=20, verbose_name='TAN Number'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='account_holder_name',
            field=models.CharField(max_length=255, verbose_name='Account Holder Name'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='account_number',
            field=models.CharField(max_length=50, verbose_name='Bank Account Number'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='authorised_districts',
            field=models.ManyToManyField(blank=True, help_text='Districts where this distributor is allowed to operate. Each district must belong to one of the selected authorised states.', related_name='authorised_distributors', to='mapwala_mis.district', verbose_name='Authorised Operating Districts'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='authorised_states',
            field=models.ManyToManyField(blank=True, help_text='States where this distributor is allowed to operate.', related_name='authorised_distributors', to='mapwala_mis.state', verbose_name='Authorised Operating States'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='bank_name',
            field=models.CharField(max_length=255, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='district',
            field=models.ForeignKey(help_text='District where the distributor is officially registered.', on_delete=django.db.models.deletion.PROTECT, related_name='distributors', to='mapwala_mis.district', verbose_name='Registered District'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='gst_document',
            field=models.FileField(upload_to='documents/distributor/gst/', verbose_name='GST Document'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='gst_number',
            field=models.CharField(max_length=20, verbose_name='GST Number'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='ifsc_code',
            field=models.CharField(max_length=20, verbose_name='IFSC Code'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='linked_to',
            field=models.CharField(choices=[('manufacturer', 'Manufacturer')], help_text='Defines the entity this distributor is linked to.', max_length=50, verbose_name='Linked To'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Required when Linked To is Manufacturer.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distributors', to='mapwala_mis.manufacturer', verbose_name='Linked Manufacturer'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Distributor Name'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='pan_document',
            field=models.FileField(upload_to='documents/distributor/pan/', verbose_name='PAN Document'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='pan_number',
            field=models.CharField(max_length=20, verbose_name='PAN Number'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='state',
            field=models.ForeignKey(help_text='State where the distributor is officially registered.', on_delete=django.db.models.deletion.PROTECT, related_name='distributors', to='mapwala_mis.state', verbose_name='Registered State'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='tan_document',
            field=models.FileField(upload_to='documents/distributor/tan/', verbose_name='TAN Document'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='tan_number',
            field=models.CharField(max_length=20, verbose_name='TAN Number'),
        ),
    ]
