# Generated by Django 6.0 on 2026-01-08 12:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0010_alter_dealer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField(help_text='Numeric Product ID shown in PI screen (e.g. 101, 102)', unique=True, verbose_name='Product ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['product_id'],
            },
        ),
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(choices=[('b2b', 'B2B Partner'), ('b2c', 'B2C Customer'), ('dealer', 'Dealer'), ('distributor', 'Distributor')], max_length=20)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('quantity', models.PositiveIntegerField()),
                ('shipping_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_terms', models.CharField(choices=[('advance', 'Advance'), ('on_delivery', 'On Delivery'), ('full', 'Full Payment'), ('partial', 'Partial Payment')], max_length=20)),
                ('delivery_date', models.DateField()),
                ('delivery_address', models.TextField()),
                ('contact_person_name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=15)),
                ('gstn', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('b2b_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mapwala_mis.b2bpartner')),
                ('b2c_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mapwala_mis.b2ccustomer')),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mapwala_mis.dealer')),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mapwala_mis.distributor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapwala_mis.product')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapwala_mis.state')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
