# Generated by Django 6.0 on 2026-01-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0011_product_proformainvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(help_text='Numeric Product ID shown in PI screen (e.g. 101, 102)', max_length=20, unique=True, verbose_name='Product ID'),
        ),
    ]
