# Generated by Django 6.0 on 2026-01-09 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0012_alter_product_product_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_type', models.CharField(choices=[('individual', 'Individual Entry'), ('bulk', 'Bulk Upload')], max_length=20)),
                ('bom_file', models.FileField(blank=True, null=True, upload_to='bom/excel/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BOMComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_mark', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('designator', models.CharField(max_length=255)),
                ('footprint', models.CharField(max_length=50)),
                ('volt', models.CharField(max_length=50)),
                ('part_no', models.CharField(max_length=100)),
                ('part_make', models.CharField(max_length=100)),
                ('per_device_quantity', models.PositiveIntegerField()),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='mapwala_mis.bom')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bom',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bom', to='mapwala_mis.device'),
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.CharField(max_length=100)),
                ('length', models.DecimalField(decimal_places=2, max_digits=8)),
                ('breadth', models.DecimalField(decimal_places=2, max_digits=8)),
                ('height', models.DecimalField(decimal_places=2, max_digits=8)),
                ('make', models.CharField(max_length=100)),
                ('part_number', models.CharField(max_length=100)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mapwala_mis.device')),
            ],
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('specifications', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='mapwala_mis.device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('variant', models.CharField(max_length=50)),
                ('state_of_supply', models.CharField(max_length=100)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='mapwala_mis.device')),
            ],
        ),
        migrations.CreateModel(
            name='Enclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=2, max_digits=8)),
                ('breadth', models.DecimalField(decimal_places=2, max_digits=8)),
                ('height', models.DecimalField(decimal_places=2, max_digits=8)),
                ('color', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('make', models.CharField(max_length=100)),
                ('part_number', models.CharField(max_length=100)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mapwala_mis.device')),
            ],
        ),
        migrations.CreateModel(
            name='SOSButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_length', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity_per_set', models.PositiveIntegerField()),
                ('make', models.CharField(max_length=100)),
                ('part_number', models.CharField(max_length=100)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mapwala_mis.device')),
            ],
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('length', models.DecimalField(decimal_places=2, max_digits=8)),
                ('breadth', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='documents/device/stickers/')),
                ('make', models.CharField(max_length=100)),
                ('part_number', models.CharField(max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapwala_mis.device')),
            ],
        ),
        migrations.CreateModel(
            name='UserManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/device/manuals/')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mapwala_mis.device')),
            ],
        ),
        migrations.CreateModel(
            name='WireHarness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_wires', models.PositiveIntegerField()),
                ('specification', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=100)),
                ('part_number', models.CharField(max_length=100)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mapwala_mis.device')),
            ],
        ),
        migrations.CreateModel(
            name='WireConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_name', models.CharField(max_length=100)),
                ('number_of_pins', models.PositiveIntegerField()),
                ('wire_colors', models.CharField(max_length=255)),
                ('wire_harness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='mapwala_mis.wireharness')),
            ],
        ),
    ]
