# Generated by Django 6.0 on 2026-01-10 09:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0013_bom_bomcomponent_device_bom_device_battery_accessory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('available_stock', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='mapwala_mis.product')),
            ],
            options={
                'ordering': ['batch_number'],
                'unique_together': {('product', 'batch_number')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('sales', 'Sales Order')], max_length=20)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_type', models.CharField(choices=[('b2c', 'B2C Customer'), ('distributor', 'Distributor'), ('dealer', 'Dealer')], max_length=20)),
                ('contact_person', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=15)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('gst_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('shipping_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_date', models.DateField()),
                ('delivery_address', models.TextField()),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('credit_card', 'Credit Card'), ('upi', 'UPI'), ('credit_terms', 'Credit Terms')], max_length=20)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('pending', 'Pending'), ('on_credit', 'On Credit')], max_length=20)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapwala_mis.batch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapwala_mis.product')),
            ],
        ),
    ]
