# Generated by Django 6.0 on 2026-01-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0014_batch_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
