# Generated by Django 6.0 on 2026-01-10 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0016_orderproduct_orderbatch_salesorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderbatch',
            options={'ordering': ['batch_number'], 'verbose_name': 'Order Batch', 'verbose_name_plural': 'Order Batches'},
        ),
    ]
