# Generated by Django 6.0 on 2026-01-12 08:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0017_alter_orderbatch_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Supplier / Vendor',
                'verbose_name_plural': 'Suppliers / Vendors',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='orderbatch',
            name='available_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_type', models.CharField(choices=[('add_to_stock', 'Add to Stock')], max_length=20)),
                ('product_category', models.CharField(choices=[('gps_devices', 'GPS Devices'), ('tracking_devices', 'Tracking Devices'), ('iot_devices', 'IoT Devices'), ('accessories', 'Accessories'), ('components', 'Components')], max_length=30)),
                ('quantity_added', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_date', models.DateField()),
                ('manufacturing_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapwala_mis.orderbatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapwala_mis.orderproduct')),
                ('supplier_vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapwala_mis.suppliervendor')),
            ],
        ),
    ]
