# Generated by Django 6.0 on 2026-01-12 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0018_suppliervendor_alter_orderbatch_available_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbatch',
            name='available_stock',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
