# Generated by Django 6.0 on 2026-01-12 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0019_alter_orderbatch_available_stock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('production', 'Production Order'), ('sales', 'Sales Order')], max_length=20)),
                ('production_type', models.CharField(blank=True, choices=[('add_to_stock', 'Add to Stock'), ('make_to_order', 'Make to Order')], max_length=20, null=True)),
                ('assembly_type', models.CharField(blank=True, choices=[('fully_outsourced', 'Fully Outsourced'), ('pcb_device', 'PCB + Device'), ('pcb_outside_device_inside', 'PCB Outside, Device Inside')], max_length=30, null=True)),
                ('is_step1_complete', models.BooleanField(default=False)),
                ('is_step2_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
