# Generated by Django 6.0 on 2026-01-13 06:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0020_orderentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEntryMakeToOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_type', models.CharField(choices=[('b2b', 'B2B Partner'), ('b2c', 'B2C Customer'), ('distributor', 'Distributor'), ('dealer', 'Dealer')], max_length=20)),
                ('contact_person', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=15)),
                ('product_specifications', models.TextField(blank=True)),
                ('customization_details', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('expected_delivery_date', models.DateField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gst_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('shipping_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('advance_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_terms', models.CharField(choices=[('100_advance', '100% Advance'), ('50_50', '50% Advance, 50% on Delivery'), ('30_70', '30% Advance, 70% on Delivery'), ('net_30', 'Net 30 Days'), ('net_60', 'Net 60 Days'), ('custom', 'Custom Terms')], max_length=20)),
                ('order_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=20)),
                ('special_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='make_to_order', to='mapwala_mis.orderentry')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapwala_mis.orderproduct')),
            ],
        ),
    ]
