# Generated by Django 6.0 on 2026-01-13 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0021_orderentrymaketoorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_reference', models.CharField(help_text='Order ID or Device Name selected in UI (e.g. ORD001)', max_length=100)),
                ('device_name', models.CharField(help_text='Device name shown in UI', max_length=255)),
                ('assembly_type', models.CharField(choices=[('pcb_assembly', 'PCB Assembly'), ('device_assembly', 'Device Assembly')], max_length=30)),
                ('quantity', models.PositiveIntegerField()),
                ('srn_no', models.CharField(blank=True, choices=[('SRN001', 'Standard Requirement - Basic GPS'), ('SRN002', 'Advanced Requirement - GPS + IoT'), ('SRN003', 'Premium Requirement - Full Suite'), ('SRN004', 'Custom Requirement - Specialized')], max_length=20, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('additional_requirements', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RFQSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('bom', 'BOM Part'), ('component', 'Component'), ('service', 'Service')], max_length=20)),
                ('reference', models.CharField(max_length=255)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='mapwala_mis.requestforquote')),
            ],
        ),
    ]
