# Generated by Django 6.0 on 2026-01-14 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0022_requestforquote_rfqselection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestforquote',
            name='device_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='requestforquote',
            name='order_reference',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rfqselection',
            name='reference',
            field=models.CharField(help_text='Selected BOM ID / Component name / Service name', max_length=255),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=255)),
                ('order_id', models.CharField(max_length=50)),
                ('rfq_id', models.CharField(max_length=50)),
                ('assembly_type', models.CharField(choices=[('pcb', 'PCB Assembly'), ('device', 'Device Assembly')], max_length=20)),
                ('wastage_percentage', models.PositiveIntegerField(default=0)),
                ('selected_vendor_id', models.CharField(max_length=50)),
                ('delivery_date', models.DateField()),
                ('payment_terms', models.CharField(choices=[('full_payment', 'Full Payment'), ('down_payment', 'Down Payment'), ('advance', 'Advance'), ('30_days', '30 Days Net'), ('60_days', '60 Days Net'), ('90_days', '90 Days Net'), ('cod', 'Cash on Delivery')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50)),
                ('item_type', models.CharField(choices=[('bom', 'BOM Item'), ('component', 'Component'), ('service', 'Service')], max_length=20)),
                ('vendor_name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_days', models.PositiveIntegerField()),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mapwala_mis.purchaseorder')),
            ],
        ),
    ]
