# Generated by Django 6.0 on 2026-01-14 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0023_alter_requestforquote_device_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='vendor_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('full_payment', 'Full Payment'), ('down_payment', 'Down Payment'), ('advance', 'Advance'), ('30_days', '30 Days Net'), ('60_days', '60 Days Net'), ('90_days', '90 Days Net'), ('cod', 'Cash on Delivery')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='selected_vendor_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='wastage_percentage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PurchaseOrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('bom', 'Items (BOM Parts)'), ('component', 'Components (Enclosure, Battery, etc.)'), ('service', 'Services (Assembly, Quality Check, etc.)')], max_length=20)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_types', to='mapwala_mis.purchaseorder')),
            ],
            options={
                'unique_together': {('purchase_order', 'order_type')},
            },
        ),
    ]
