# Generated by Django 6.0 on 2026-01-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0024_purchaseorderitem_vendor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='vendor_id',
            field=models.CharField(max_length=50),
        ),
    ]
