# Generated by Django 6.0 on 2026-01-14 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0025_alter_purchaseorderitem_vendor_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialReceiptNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_date', models.DateField()),
                ('inward_type', models.CharField(choices=[('bom_items', 'BOM Items'), ('materials', 'Materials'), ('assembled_pcb', 'Assembled PCB'), ('assembled_device', 'Assembled Device')], max_length=30)),
                ('receipt_date', models.DateField()),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('delivery_challan_number', models.CharField(blank=True, max_length=50)),
                ('eway_bill_number', models.CharField(blank=True, max_length=50)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='mrn/invoice/')),
                ('challan_file', models.FileField(blank=True, null=True, upload_to='mrn/challan/')),
                ('eway_bill_file', models.FileField(blank=True, null=True, upload_to='mrn/eway/')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mrns', to='mapwala_mis.purchaseorder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mrns', to='mapwala_mis.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_qty', models.PositiveIntegerField()),
                ('serial_numbers', models.TextField(blank=True, help_text='Comma separated serial numbers')),
                ('balance_qty', models.PositiveIntegerField()),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mrn_items', to='mapwala_mis.purchaseorderitem')),
                ('mrn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mapwala_mis.materialreceiptnote')),
            ],
        ),
    ]
