# Generated by Django 6.0 on 2026-01-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0026_materialreceiptnote_materialreceiptitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
