# Generated by Django 6.0 on 2026-01-15 06:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0027_purchaseorderitem_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell_from_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PostDispatchReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_id', models.CharField(max_length=50)),
                ('invoice_no', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=255)),
                ('dispatch_total_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('return_type', models.CharField(choices=[('full', 'Full Return (All Items)'), ('partial', 'Partial Return (Some Items)'), ('replacement', 'Return for Replacement')], max_length=20)),
                ('return_reason', models.CharField(choices=[('damaged', 'Damaged in Transit'), ('defective', 'Defective Product'), ('wrong_item', 'Wrong Item Delivered'), ('rejected', 'Customer Rejection'), ('quality', 'Quality Issues'), ('spec_mismatch', 'Specification Mismatch'), ('other', 'Other')], max_length=20)),
                ('return_date', models.DateField()),
                ('return_remarks', models.TextField(blank=True)),
                ('total_return_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PostDispatchReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('dispatched_qty', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('return_qty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('return_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('post_dispatch_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mapwala_mis.postdispatchreturn')),
            ],
        ),
    ]
