# Generated by Django 6.0 on 2026-01-15 09:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0028_sell_from_stock_postdispatchreturn_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('distributor', 'Distributor'), ('dealer', 'Dealer'), ('b2c', 'B2C Customer')], max_length=20)),
                ('dispatch_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('imei_number', models.CharField(blank=True, max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=50)),
                ('iccid_number', models.CharField(blank=True, max_length=50)),
                ('dispatch_date', models.DateField()),
                ('dispatch_remarks', models.TextField(blank=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_contact', models.CharField(max_length=15)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_address', models.TextField()),
                ('urgent_delivery_required', models.BooleanField(default=False)),
                ('insurance_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapwala_mis.orderbatch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapwala_mis.orderproduct')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='mapwala_mis.salesorder')),
            ],
            options={
                'verbose_name': 'Dispatch',
                'verbose_name_plural': 'Dispatches',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='Sell_from_stock',
        ),
    ]
