# Generated by Django 6.0 on 2026-01-15 09:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0029_dispatch_delete_sell_from_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispatch',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mapwala_mis.orderbatch'),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='customer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='customer_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dispatch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dispatch_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mapwala_mis.orderproduct'),
        ),
    ]
