# Generated by Django 6.0 on 2026-01-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0030_alter_dispatch_options_alter_dispatch_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='stock_deducted',
            field=models.BooleanField(default=False),
        ),
    ]
