# Generated by Django 6.0 on 2026-01-16 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0031_dispatch_status_dispatch_stock_deducted'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('aadhar_number', models.CharField(max_length=20)),
                ('aadhar_document', models.FileField(upload_to='documents/aadhar/')),
                ('pan_number', models.CharField(max_length=20)),
                ('pan_document', models.FileField(upload_to='documents/pan/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_registrations', to='mapwala_mis.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_registrations', to='mapwala_mis.state')),
            ],
        ),
    ]
