# Generated by Django 6.0 on 2026-01-16 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0032_accountregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseDepartmentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_department_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('aadhar_number', models.CharField(max_length=20)),
                ('aadhar_document', models.FileField(upload_to='documents/purchase_department/aadhar/')),
                ('pan_number', models.CharField(max_length=20)),
                ('pan_document', models.FileField(upload_to='documents/purchase_department/pan/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_departments', to='mapwala_mis.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_departments', to='mapwala_mis.state')),
            ],
        ),
        migrations.CreateModel(
            name='QCInspectorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qc_inspector_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('aadhar_number', models.CharField(max_length=20)),
                ('aadhar_document', models.FileField(upload_to='documents/qc_inspector/aadhar/')),
                ('pan_number', models.CharField(max_length=20)),
                ('pan_document', models.FileField(upload_to='documents/qc_inspector/pan/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_inspectors', to='mapwala_mis.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_inspectors', to='mapwala_mis.state')),
            ],
        ),
        migrations.CreateModel(
            name='RepairTechnicianRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_technician_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('aadhar_number', models.CharField(max_length=20)),
                ('aadhar_document', models.FileField(upload_to='documents/repair_technician/aadhar/')),
                ('pan_number', models.CharField(max_length=20)),
                ('pan_document', models.FileField(upload_to='documents/repair_technician/pan/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_technicians', to='mapwala_mis.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_technicians', to='mapwala_mis.state')),
            ],
        ),
        migrations.CreateModel(
            name='StoreManagerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_manager_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('aadhar_number', models.CharField(max_length=20)),
                ('aadhar_document', models.FileField(upload_to='documents/store_manager/aadhar/')),
                ('pan_number', models.CharField(max_length=20)),
                ('pan_document', models.FileField(upload_to='documents/store_manager/pan/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_managers', to='mapwala_mis.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_managers', to='mapwala_mis.state')),
            ],
        ),
    ]
