# Generated by Django 6.0 on 2026-01-16 12:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0033_purchasedepartmentregistration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoreTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('transfer_id', models.CharField(max_length=50, unique=True)),
                ('mrn_number', models.CharField(blank=True, max_length=50, null=True)),
                ('batch_number', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('transfer_date', models.DateField()),
                ('dispatch_status', models.CharField(choices=[('dispatched', 'Dispatched'), ('non_dispatched', 'Non-dispatched'), ('return', 'Return')], default='non_dispatched', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_transfers', to='mapwala_mis.productcategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_store_transfers', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_transfers', to='mapwala_mis.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_transfers', to='mapwala_mis.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transfer_id'], name='mapwala_mis_transfe_a31e06_idx'), models.Index(fields=['batch_number'], name='mapwala_mis_batch_n_4d529c_idx'), models.Index(fields=['dispatch_status'], name='mapwala_mis_dispatc_562f2f_idx'), models.Index(fields=['transfer_date'], name='mapwala_mis_transfe_56e23d_idx')],
            },
        ),
    ]
