# Generated by Django 6.0 on 2026-01-17 04:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0034_productcategory_storetransfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('date', models.DateField()),
                ('customer', models.CharField(max_length=255)),
                ('reason', models.CharField(choices=[('return_accepted', 'Return Accepted'), ('discount_adjustment', 'Discount Adjustment'), ('overpayment_refund', 'Overpayment Refund'), ('quality_issue', 'Quality Issue'), ('price_correction', 'Price Correction'), ('other', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processed', 'Processed')], db_index=True, default='pending', max_length=20)),
                ('reference_document', models.CharField(blank=True, help_text='e.g., INV-001, RTN-001', max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_credit_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='mapwala_mis_status_ab5ea5_idx'), models.Index(fields=['date'], name='mapwala_mis_date_ebd40e_idx'), models.Index(fields=['customer'], name='mapwala_mis_custome_a5288d_idx')],
            },
        ),
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('date', models.DateField()),
                ('vendor', models.CharField(max_length=255)),
                ('reason', models.CharField(choices=[('vendor_rejected_return', 'Vendor Rejected Return'), ('quality_dispute', 'Quality Dispute'), ('late_delivery_penalty', 'Late Delivery Penalty'), ('specification_mismatch', 'Specification Mismatch'), ('warranty_claim_denied', 'Warranty Claim Denied'), ('other', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processed', 'Processed')], db_index=True, default='pending', max_length=20)),
                ('reference_document', models.CharField(blank=True, help_text='e.g., RTN-001, PO-001', max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_debit_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='mapwala_mis_status_940066_idx'), models.Index(fields=['date'], name='mapwala_mis_date_139e9d_idx'), models.Index(fields=['vendor'], name='mapwala_mis_vendor_9be29f_idx')],
            },
        ),
    ]
