# Generated by Django 6.0 on 2026-01-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0035_creditnote_debitnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('note_type', models.CharField(choices=[('debit', 'Debit Note'), ('credit', 'Credit Note')], max_length=10)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('year', 'note_type')},
            },
        ),
    ]
