# Generated by Django 6.0 on 2026-01-20 06:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0037_rejecteditem_repairrecord_returnrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('gst_rate', models.DecimalField(choices=[(Decimal('0.00'), '0%'), (Decimal('5.00'), '5%'), (Decimal('12.00'), '12%'), (Decimal('18.00'), '18%'), (Decimal('28.00'), '28%')], decimal_places=2, max_digits=5)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('delivery_date', models.DateField()),
                ('delivery_address', models.TextField()),
                ('purpose_remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='self_orders', to='mapwala_mis.device')),
                ('supply_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='self_orders', to='mapwala_mis.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='self_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='mapwala_mis_user_id_1d58ba_idx'), models.Index(fields=['device'], name='mapwala_mis_device__77e063_idx'), models.Index(fields=['supply_state'], name='mapwala_mis_supply__95285a_idx')],
            },
        ),
    ]
