# Generated by Django 6.0 on 2026-01-20 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0039_quotation_quotationitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='gst_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/vendor/gst/'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='gst_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='pan_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/vendor/pan/'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='pan_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='tan_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/vendor/tan/'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='tan_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='quotationitem',
            unique_together={('quotation', 'item_id')},
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['user'], name='mapwala_mis_user_id_940458_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['email'], name='mapwala_mis_email_80d87b_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['phone_number'], name='mapwala_mis_phone_n_416bfe_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['gst_number'], name='mapwala_mis_gst_num_338c00_idx'),
        ),
    ]
