# Generated by Django 6.0 on 2026-01-21 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapwala_mis', '0041_alter_vendor_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vendor',
            name='mapwala_mis_user_id_940458_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendor',
            name='mapwala_mis_email_80d87b_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendor',
            name='mapwala_mis_phone_n_416bfe_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendor',
            name='mapwala_mis_gst_num_338c00_idx',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='gst_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='pan_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='tan_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='vendor',
            unique_together={('user', 'gst_number')},
        ),
    ]
